/* Generated by tools/make_deepseek_v41_engram_fixture.py: what the C side must
 * reproduce when it rebuilds the token map from the packed header. The
 * fingerprint covers every one of the entries, the samples make a failure
 * readable. */
#ifndef COLIBRI_DEEPSEEK_V41_ENGRAM_MAP_CHECKS_H
#define COLIBRI_DEEPSEEK_V41_ENGRAM_MAP_CHECKS_H

#include <stdint.h>

#define COLI_V41_ENGRAM_MAP_TOKEN_COUNT 129280
#define COLI_V41_ENGRAM_MAP_CLASS_COUNT 99092

typedef struct {
    int token_id;
    uint32_t class_id;
} ColiV41EngramMapSample;

/* token      0 -> class 0 */
/* token      1 -> class 1 */
/* token      2 -> class 2 */
/* token      3 -> class 3 */
/* token    100 -> class 74 */
/* token    127 -> class 101 */
/* token   1000 -> class 604 */
/* token   5000 -> class 4191 */
/* token  99091 -> class 75710 */
/* token 128000 -> class 97812 */
/* token 129279 -> class 99091 */
static const ColiV41EngramMapSample coli_v41_engram_map_samples[] = {
    { 0, 0 },
    { 1, 1 },
    { 2, 2 },
    { 3, 3 },
    { 100, 74 },
    { 127, 101 },
    { 1000, 604 },
    { 5000, 4191 },
    { 99091, 75710 },
    { 128000, 97812 },
    { 129279, 99091 },
};
static const int coli_v41_engram_map_sample_count = 11;
static const uint64_t coli_v41_engram_map_expected_fnv1a64 = UINT64_C(0x6b5cfa68a5f57ba6);

#endif /* COLIBRI_DEEPSEEK_V41_ENGRAM_MAP_CHECKS_H */
